### ISSUE TITLE
Support for MacOS Sonoma 14?

### ISSUE THREAD

**Issue by greenerycomplexity** [bpetrynski/alfred-notification-dismisser#4]
Hi,

I just came across this repo after browsing on Reddit, I tried it out and it seemed like this workflow no longer works with Sonoma, nor does it return any particular error so I'm not sure where to even start on fixing it. 

Do you have any plans on adding support for Sonoma?

**Comment by bpetrynski** [comment]
Should be working now 😉

**Comment by greenerycomplexity** [comment]
Thank you so much! Works beautifully, especially for the pesky "External disk not ejected properly" notifications, although that's my own fault haha.

 Is there a way for this workflow to clear out the entire notification centre as well? I would love for it to be in the same workflow but just using different keywords e.g "zap" or something
 
 I got this script below from [someone on Reddit](https://www.reddit.com/r/MacOS/comments/qo3khz/comment/j3v2h1c/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) that should be able to open the Notifications Centre and clear things out, but I'm not fully sure how to implement it in an Alfred workflow.
 
 ```
---- zap Notifications queue items
tell application "System Events"
	tell process "NotificationCenter"
		set numwins to (count windows)
		repeat with i from numwins to 1 by -1
			click button "Close" of window i
		end repeat
	end tell
end tell
```

**Comment by henderea** [comment]
Just open the Notification Center and use the workflow while it's open. I have the workflow set to a keyboard shortcut and it works fine for clearing out the Notification Center when it's open. On Monterey, at least.

**Comment by greenerycomplexity** [comment]
Is there a way to open the Notifications Centre first with the script as well? I've got a bunch of global shortcuts already and it's pretty hard to keep track of them all.

**Comment by bpetrynski** [comment]
Already supported 🫡
